# Generated by Django 5.1.6 on 2025-02-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_account_balance_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
